# Generated by Django 4.2.13 on 2024-06-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.JSONField(null=True)),
                (
                    "member_picture_mobile",
                    models.ImageField(
                        max_length=200, upload_to="images/mobile_images/member_images/"
                    ),
                ),
                (
                    "member_picture_web",
                    models.ImageField(
                        max_length=200, upload_to="images/web_images/member_images/"
                    ),
                ),
                ("member_position", models.JSONField(null=True)),
                ("member_desc", models.JSONField(null=True)),
                ("member_skills", models.JSONField(null=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_field", models.JSONField(null=True)),
                ("project_name", models.JSONField(null=True)),
                ("project_link", models.URLField(blank=True, null=True)),
                ("project_desc", models.JSONField(null=True)),
                ("is_company", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField(max_length=30)),
                (
                    "section_image_mobile",
                    models.ImageField(
                        max_length=200, upload_to="images/mobile_images/section_images/"
                    ),
                ),
                (
                    "section_image_web",
                    models.ImageField(
                        max_length=200, upload_to="images/web_images/section_images/"
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField()),
                (
                    "service_icon",
                    models.ImageField(
                        max_length=200, upload_to="images/service_icons/"
                    ),
                ),
                (
                    "service_picture_mobile",
                    models.ImageField(
                        max_length=200, upload_to="images/mobile_images/service_images/"
                    ),
                ),
                (
                    "service_picture_web",
                    models.ImageField(
                        max_length=200, upload_to="images/web_images/service_images/"
                    ),
                ),
                ("service_description", models.JSONField()),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Project_Picture_web",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture_title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        max_length=200, upload_to="images/web_images/project_images/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_pictures",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Project_Picture_mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture_title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        max_length=200, upload_to="images/mobile_images/project_images/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_pictures",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.section"
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField()),
                (
                    "image_mobile",
                    models.ImageField(
                        max_length=200, upload_to="images/mobile_images/course_images/"
                    ),
                ),
                (
                    "image_web",
                    models.ImageField(
                        max_length=200, upload_to="images/web_images/course_images/"
                    ),
                ),
                ("desc", models.JSONField()),
                ("teacher", models.JSONField()),
                ("time", models.JSONField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.section"
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Student_Project_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("university_name", models.CharField(max_length=30)),
                ("phone", models.BigIntegerField(default=None)),
                ("desc", models.CharField(default=None, max_length=500)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "phone", "project")},
            },
        ),
        migrations.CreateModel(
            name="Student_Course_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.BigIntegerField(default=None)),
                ("desc", models.CharField(default=None, max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "phone", "course")},
            },
        ),
        migrations.CreateModel(
            name="Company_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("desc", models.TextField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
            options={
                "unique_together": {("agent_name", "company_name", "service")},
            },
        ),
    ]
